//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance
    {
        public int? InsuranceId { get; set; }
        public string Name { get; set; }
        public string DescriptionInsurance { get; set; }
        public Nullable<int> TypeCoveringId { get; set; }
        public Nullable<decimal> Coverage { get; set; }
        public Nullable<System.DateTime> StartValidity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> TypeRiskId { get; set; }
    }
}
